// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: playground/options/v1/business_term_options.proto

package playground.v1;

public final class BusinessTermOptionsOuterClass {
  private BusinessTermOptionsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(playground.v1.BusinessTermOptionsOuterClass.bizTerm);
    registry.add(playground.v1.BusinessTermOptionsOuterClass.doc);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BusinessTermOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:playground.v1.BusinessTermOptions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string def = 2[json_name = "def"];</code>
     * @return Whether the def field is set.
     */
    boolean hasDef();
    /**
     * <code>optional string def = 2[json_name = "def"];</code>
     * @return The def.
     */
    java.lang.String getDef();
    /**
     * <code>optional string def = 2[json_name = "def"];</code>
     * @return The bytes for def.
     */
    com.google.protobuf.ByteString
        getDefBytes();

    /**
     * <code>optional string source_name = 3[json_name = "sourceName"];</code>
     * @return Whether the sourceName field is set.
     */
    boolean hasSourceName();
    /**
     * <code>optional string source_name = 3[json_name = "sourceName"];</code>
     * @return The sourceName.
     */
    java.lang.String getSourceName();
    /**
     * <code>optional string source_name = 3[json_name = "sourceName"];</code>
     * @return The bytes for sourceName.
     */
    com.google.protobuf.ByteString
        getSourceNameBytes();

    /**
     * <code>optional string source_uri = 4[json_name = "sourceUri"];</code>
     * @return Whether the sourceUri field is set.
     */
    boolean hasSourceUri();
    /**
     * <code>optional string source_uri = 4[json_name = "sourceUri"];</code>
     * @return The sourceUri.
     */
    java.lang.String getSourceUri();
    /**
     * <code>optional string source_uri = 4[json_name = "sourceUri"];</code>
     * @return The bytes for sourceUri.
     */
    com.google.protobuf.ByteString
        getSourceUriBytes();
  }
  /**
   * Protobuf type {@code playground.v1.BusinessTermOptions}
   */
  public static final class BusinessTermOptions extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:playground.v1.BusinessTermOptions)
      BusinessTermOptionsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BusinessTermOptions.newBuilder() to construct.
    private BusinessTermOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BusinessTermOptions() {
      def_ = "";
      sourceName_ = "";
      sourceUri_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BusinessTermOptions();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BusinessTermOptions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              def_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              sourceName_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              sourceUri_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return playground.v1.BusinessTermOptionsOuterClass.internal_static_playground_v1_BusinessTermOptions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return playground.v1.BusinessTermOptionsOuterClass.internal_static_playground_v1_BusinessTermOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions.class, playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions.Builder.class);
    }

    private int bitField0_;
    public static final int DEF_FIELD_NUMBER = 2;
    private volatile java.lang.Object def_;
    /**
     * <code>optional string def = 2[json_name = "def"];</code>
     * @return Whether the def field is set.
     */
    @java.lang.Override
    public boolean hasDef() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string def = 2[json_name = "def"];</code>
     * @return The def.
     */
    @java.lang.Override
    public java.lang.String getDef() {
      java.lang.Object ref = def_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          def_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string def = 2[json_name = "def"];</code>
     * @return The bytes for def.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDefBytes() {
      java.lang.Object ref = def_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        def_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCE_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object sourceName_;
    /**
     * <code>optional string source_name = 3[json_name = "sourceName"];</code>
     * @return Whether the sourceName field is set.
     */
    @java.lang.Override
    public boolean hasSourceName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string source_name = 3[json_name = "sourceName"];</code>
     * @return The sourceName.
     */
    @java.lang.Override
    public java.lang.String getSourceName() {
      java.lang.Object ref = sourceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sourceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string source_name = 3[json_name = "sourceName"];</code>
     * @return The bytes for sourceName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSourceNameBytes() {
      java.lang.Object ref = sourceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCE_URI_FIELD_NUMBER = 4;
    private volatile java.lang.Object sourceUri_;
    /**
     * <code>optional string source_uri = 4[json_name = "sourceUri"];</code>
     * @return Whether the sourceUri field is set.
     */
    @java.lang.Override
    public boolean hasSourceUri() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string source_uri = 4[json_name = "sourceUri"];</code>
     * @return The sourceUri.
     */
    @java.lang.Override
    public java.lang.String getSourceUri() {
      java.lang.Object ref = sourceUri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sourceUri_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string source_uri = 4[json_name = "sourceUri"];</code>
     * @return The bytes for sourceUri.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSourceUriBytes() {
      java.lang.Object ref = sourceUri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, def_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sourceName_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sourceUri_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, def_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sourceName_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sourceUri_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions)) {
        return super.equals(obj);
      }
      playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions other = (playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions) obj;

      if (hasDef() != other.hasDef()) return false;
      if (hasDef()) {
        if (!getDef()
            .equals(other.getDef())) return false;
      }
      if (hasSourceName() != other.hasSourceName()) return false;
      if (hasSourceName()) {
        if (!getSourceName()
            .equals(other.getSourceName())) return false;
      }
      if (hasSourceUri() != other.hasSourceUri()) return false;
      if (hasSourceUri()) {
        if (!getSourceUri()
            .equals(other.getSourceUri())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDef()) {
        hash = (37 * hash) + DEF_FIELD_NUMBER;
        hash = (53 * hash) + getDef().hashCode();
      }
      if (hasSourceName()) {
        hash = (37 * hash) + SOURCE_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getSourceName().hashCode();
      }
      if (hasSourceUri()) {
        hash = (37 * hash) + SOURCE_URI_FIELD_NUMBER;
        hash = (53 * hash) + getSourceUri().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code playground.v1.BusinessTermOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:playground.v1.BusinessTermOptions)
        playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return playground.v1.BusinessTermOptionsOuterClass.internal_static_playground_v1_BusinessTermOptions_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return playground.v1.BusinessTermOptionsOuterClass.internal_static_playground_v1_BusinessTermOptions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions.class, playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions.Builder.class);
      }

      // Construct using playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        def_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sourceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        sourceUri_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return playground.v1.BusinessTermOptionsOuterClass.internal_static_playground_v1_BusinessTermOptions_descriptor;
      }

      @java.lang.Override
      public playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions getDefaultInstanceForType() {
        return playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions.getDefaultInstance();
      }

      @java.lang.Override
      public playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions build() {
        playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions buildPartial() {
        playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions result = new playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.def_ = def_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sourceName_ = sourceName_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sourceUri_ = sourceUri_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions) {
          return mergeFrom((playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions other) {
        if (other == playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions.getDefaultInstance()) return this;
        if (other.hasDef()) {
          bitField0_ |= 0x00000001;
          def_ = other.def_;
          onChanged();
        }
        if (other.hasSourceName()) {
          bitField0_ |= 0x00000002;
          sourceName_ = other.sourceName_;
          onChanged();
        }
        if (other.hasSourceUri()) {
          bitField0_ |= 0x00000004;
          sourceUri_ = other.sourceUri_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object def_ = "";
      /**
       * <code>optional string def = 2[json_name = "def"];</code>
       * @return Whether the def field is set.
       */
      public boolean hasDef() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string def = 2[json_name = "def"];</code>
       * @return The def.
       */
      public java.lang.String getDef() {
        java.lang.Object ref = def_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            def_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string def = 2[json_name = "def"];</code>
       * @return The bytes for def.
       */
      public com.google.protobuf.ByteString
          getDefBytes() {
        java.lang.Object ref = def_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          def_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string def = 2[json_name = "def"];</code>
       * @param value The def to set.
       * @return This builder for chaining.
       */
      public Builder setDef(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        def_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string def = 2[json_name = "def"];</code>
       * @return This builder for chaining.
       */
      public Builder clearDef() {
        bitField0_ = (bitField0_ & ~0x00000001);
        def_ = getDefaultInstance().getDef();
        onChanged();
        return this;
      }
      /**
       * <code>optional string def = 2[json_name = "def"];</code>
       * @param value The bytes for def to set.
       * @return This builder for chaining.
       */
      public Builder setDefBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        def_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sourceName_ = "";
      /**
       * <code>optional string source_name = 3[json_name = "sourceName"];</code>
       * @return Whether the sourceName field is set.
       */
      public boolean hasSourceName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string source_name = 3[json_name = "sourceName"];</code>
       * @return The sourceName.
       */
      public java.lang.String getSourceName() {
        java.lang.Object ref = sourceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sourceName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string source_name = 3[json_name = "sourceName"];</code>
       * @return The bytes for sourceName.
       */
      public com.google.protobuf.ByteString
          getSourceNameBytes() {
        java.lang.Object ref = sourceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string source_name = 3[json_name = "sourceName"];</code>
       * @param value The sourceName to set.
       * @return This builder for chaining.
       */
      public Builder setSourceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sourceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string source_name = 3[json_name = "sourceName"];</code>
       * @return This builder for chaining.
       */
      public Builder clearSourceName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sourceName_ = getDefaultInstance().getSourceName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string source_name = 3[json_name = "sourceName"];</code>
       * @param value The bytes for sourceName to set.
       * @return This builder for chaining.
       */
      public Builder setSourceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sourceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sourceUri_ = "";
      /**
       * <code>optional string source_uri = 4[json_name = "sourceUri"];</code>
       * @return Whether the sourceUri field is set.
       */
      public boolean hasSourceUri() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string source_uri = 4[json_name = "sourceUri"];</code>
       * @return The sourceUri.
       */
      public java.lang.String getSourceUri() {
        java.lang.Object ref = sourceUri_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sourceUri_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string source_uri = 4[json_name = "sourceUri"];</code>
       * @return The bytes for sourceUri.
       */
      public com.google.protobuf.ByteString
          getSourceUriBytes() {
        java.lang.Object ref = sourceUri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourceUri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string source_uri = 4[json_name = "sourceUri"];</code>
       * @param value The sourceUri to set.
       * @return This builder for chaining.
       */
      public Builder setSourceUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sourceUri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string source_uri = 4[json_name = "sourceUri"];</code>
       * @return This builder for chaining.
       */
      public Builder clearSourceUri() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sourceUri_ = getDefaultInstance().getSourceUri();
        onChanged();
        return this;
      }
      /**
       * <code>optional string source_uri = 4[json_name = "sourceUri"];</code>
       * @param value The bytes for sourceUri to set.
       * @return This builder for chaining.
       */
      public Builder setSourceUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sourceUri_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:playground.v1.BusinessTermOptions)
    }

    // @@protoc_insertion_point(class_scope:playground.v1.BusinessTermOptions)
    private static final playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions();
    }

    public static playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BusinessTermOptions>
        PARSER = new com.google.protobuf.AbstractParser<BusinessTermOptions>() {
      @java.lang.Override
      public BusinessTermOptions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BusinessTermOptions(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BusinessTermOptions> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BusinessTermOptions> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int BIZ_TERM_FIELD_NUMBER = 51234;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions> bizTerm = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions.class,
        playground.v1.BusinessTermOptionsOuterClass.BusinessTermOptions.getDefaultInstance());
  public static final int DOC_FIELD_NUMBER = 51235;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> doc = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_playground_v1_BusinessTermOptions_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_playground_v1_BusinessTermOptions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1playground/options/v1/business_term_op" +
      "tions.proto\022\rplayground.v1\032 google/proto" +
      "buf/descriptor.proto\"g\n\023BusinessTermOpti" +
      "ons\022\020\n\003def\030\002 \001(\tR\003def\022\037\n\013source_name\030\003 \001" +
      "(\tR\nsourceName\022\035\n\nsource_uri\030\004 \001(\tR\tsour" +
      "ceUri:`\n\010biz_term\022\037.google.protobuf.Mess" +
      "ageOptions\030\242\220\003 \001(\0132\".playground.v1.Busin" +
      "essTermOptionsR\007bizTerm:3\n\003doc\022\037.google." +
      "protobuf.MessageOptions\030\243\220\003 \001(\tR\003doc"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_playground_v1_BusinessTermOptions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_playground_v1_BusinessTermOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_playground_v1_BusinessTermOptions_descriptor,
        new java.lang.String[] { "Def", "SourceName", "SourceUri", });
    bizTerm.internalInit(descriptor.getExtensions().get(0));
    doc.internalInit(descriptor.getExtensions().get(1));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
