// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: playground/v1/message_sample.proto

package playground.v1;

public final class MessageSampleOuterClass {
  private MessageSampleOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageSampleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:playground.v1.MessageSample)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *topic field documentation
     * </pre>
     *
     * <code>int32 topic = 1;</code>
     * @return The topic.
     */
    int getTopic();

    /**
     * <pre>
     *name field documentation
     * </pre>
     *
     * <code>.playground.v1.Name name = 2;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <pre>
     *name field documentation
     * </pre>
     *
     * <code>.playground.v1.Name name = 2;</code>
     * @return The name.
     */
    playground.v1.NameOuterClass.Name getName();
    /**
     * <pre>
     *name field documentation
     * </pre>
     *
     * <code>.playground.v1.Name name = 2;</code>
     */
    playground.v1.NameOuterClass.NameOrBuilder getNameOrBuilder();
  }
  /**
   * <pre>
   *Sample Documentation
   * </pre>
   *
   * Protobuf type {@code playground.v1.MessageSample}
   */
  public static final class MessageSample extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:playground.v1.MessageSample)
      MessageSampleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageSample.newBuilder() to construct.
    private MessageSample(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageSample() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageSample();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageSample(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              topic_ = input.readInt32();
              break;
            }
            case 18: {
              playground.v1.NameOuterClass.Name.Builder subBuilder = null;
              if (name_ != null) {
                subBuilder = name_.toBuilder();
              }
              name_ = input.readMessage(playground.v1.NameOuterClass.Name.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(name_);
                name_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return playground.v1.MessageSampleOuterClass.internal_static_playground_v1_MessageSample_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return playground.v1.MessageSampleOuterClass.internal_static_playground_v1_MessageSample_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              playground.v1.MessageSampleOuterClass.MessageSample.class, playground.v1.MessageSampleOuterClass.MessageSample.Builder.class);
    }

    public static final int TOPIC_FIELD_NUMBER = 1;
    private int topic_;
    /**
     * <pre>
     *topic field documentation
     * </pre>
     *
     * <code>int32 topic = 1;</code>
     * @return The topic.
     */
    @java.lang.Override
    public int getTopic() {
      return topic_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private playground.v1.NameOuterClass.Name name_;
    /**
     * <pre>
     *name field documentation
     * </pre>
     *
     * <code>.playground.v1.Name name = 2;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return name_ != null;
    }
    /**
     * <pre>
     *name field documentation
     * </pre>
     *
     * <code>.playground.v1.Name name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public playground.v1.NameOuterClass.Name getName() {
      return name_ == null ? playground.v1.NameOuterClass.Name.getDefaultInstance() : name_;
    }
    /**
     * <pre>
     *name field documentation
     * </pre>
     *
     * <code>.playground.v1.Name name = 2;</code>
     */
    @java.lang.Override
    public playground.v1.NameOuterClass.NameOrBuilder getNameOrBuilder() {
      return getName();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (topic_ != 0) {
        output.writeInt32(1, topic_);
      }
      if (name_ != null) {
        output.writeMessage(2, getName());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (topic_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, topic_);
      }
      if (name_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getName());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof playground.v1.MessageSampleOuterClass.MessageSample)) {
        return super.equals(obj);
      }
      playground.v1.MessageSampleOuterClass.MessageSample other = (playground.v1.MessageSampleOuterClass.MessageSample) obj;

      if (getTopic()
          != other.getTopic()) return false;
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOPIC_FIELD_NUMBER;
      hash = (53 * hash) + getTopic();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static playground.v1.MessageSampleOuterClass.MessageSample parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static playground.v1.MessageSampleOuterClass.MessageSample parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static playground.v1.MessageSampleOuterClass.MessageSample parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static playground.v1.MessageSampleOuterClass.MessageSample parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static playground.v1.MessageSampleOuterClass.MessageSample parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static playground.v1.MessageSampleOuterClass.MessageSample parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static playground.v1.MessageSampleOuterClass.MessageSample parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static playground.v1.MessageSampleOuterClass.MessageSample parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static playground.v1.MessageSampleOuterClass.MessageSample parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static playground.v1.MessageSampleOuterClass.MessageSample parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static playground.v1.MessageSampleOuterClass.MessageSample parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static playground.v1.MessageSampleOuterClass.MessageSample parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(playground.v1.MessageSampleOuterClass.MessageSample prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *Sample Documentation
     * </pre>
     *
     * Protobuf type {@code playground.v1.MessageSample}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:playground.v1.MessageSample)
        playground.v1.MessageSampleOuterClass.MessageSampleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return playground.v1.MessageSampleOuterClass.internal_static_playground_v1_MessageSample_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return playground.v1.MessageSampleOuterClass.internal_static_playground_v1_MessageSample_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                playground.v1.MessageSampleOuterClass.MessageSample.class, playground.v1.MessageSampleOuterClass.MessageSample.Builder.class);
      }

      // Construct using playground.v1.MessageSampleOuterClass.MessageSample.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        topic_ = 0;

        if (nameBuilder_ == null) {
          name_ = null;
        } else {
          name_ = null;
          nameBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return playground.v1.MessageSampleOuterClass.internal_static_playground_v1_MessageSample_descriptor;
      }

      @java.lang.Override
      public playground.v1.MessageSampleOuterClass.MessageSample getDefaultInstanceForType() {
        return playground.v1.MessageSampleOuterClass.MessageSample.getDefaultInstance();
      }

      @java.lang.Override
      public playground.v1.MessageSampleOuterClass.MessageSample build() {
        playground.v1.MessageSampleOuterClass.MessageSample result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public playground.v1.MessageSampleOuterClass.MessageSample buildPartial() {
        playground.v1.MessageSampleOuterClass.MessageSample result = new playground.v1.MessageSampleOuterClass.MessageSample(this);
        result.topic_ = topic_;
        if (nameBuilder_ == null) {
          result.name_ = name_;
        } else {
          result.name_ = nameBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof playground.v1.MessageSampleOuterClass.MessageSample) {
          return mergeFrom((playground.v1.MessageSampleOuterClass.MessageSample)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(playground.v1.MessageSampleOuterClass.MessageSample other) {
        if (other == playground.v1.MessageSampleOuterClass.MessageSample.getDefaultInstance()) return this;
        if (other.getTopic() != 0) {
          setTopic(other.getTopic());
        }
        if (other.hasName()) {
          mergeName(other.getName());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        playground.v1.MessageSampleOuterClass.MessageSample parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (playground.v1.MessageSampleOuterClass.MessageSample) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int topic_ ;
      /**
       * <pre>
       *topic field documentation
       * </pre>
       *
       * <code>int32 topic = 1;</code>
       * @return The topic.
       */
      @java.lang.Override
      public int getTopic() {
        return topic_;
      }
      /**
       * <pre>
       *topic field documentation
       * </pre>
       *
       * <code>int32 topic = 1;</code>
       * @param value The topic to set.
       * @return This builder for chaining.
       */
      public Builder setTopic(int value) {
        
        topic_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *topic field documentation
       * </pre>
       *
       * <code>int32 topic = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTopic() {
        
        topic_ = 0;
        onChanged();
        return this;
      }

      private playground.v1.NameOuterClass.Name name_;
      private com.google.protobuf.SingleFieldBuilderV3<
          playground.v1.NameOuterClass.Name, playground.v1.NameOuterClass.Name.Builder, playground.v1.NameOuterClass.NameOrBuilder> nameBuilder_;
      /**
       * <pre>
       *name field documentation
       * </pre>
       *
       * <code>.playground.v1.Name name = 2;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return nameBuilder_ != null || name_ != null;
      }
      /**
       * <pre>
       *name field documentation
       * </pre>
       *
       * <code>.playground.v1.Name name = 2;</code>
       * @return The name.
       */
      public playground.v1.NameOuterClass.Name getName() {
        if (nameBuilder_ == null) {
          return name_ == null ? playground.v1.NameOuterClass.Name.getDefaultInstance() : name_;
        } else {
          return nameBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *name field documentation
       * </pre>
       *
       * <code>.playground.v1.Name name = 2;</code>
       */
      public Builder setName(playground.v1.NameOuterClass.Name value) {
        if (nameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          name_ = value;
          onChanged();
        } else {
          nameBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *name field documentation
       * </pre>
       *
       * <code>.playground.v1.Name name = 2;</code>
       */
      public Builder setName(
          playground.v1.NameOuterClass.Name.Builder builderForValue) {
        if (nameBuilder_ == null) {
          name_ = builderForValue.build();
          onChanged();
        } else {
          nameBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *name field documentation
       * </pre>
       *
       * <code>.playground.v1.Name name = 2;</code>
       */
      public Builder mergeName(playground.v1.NameOuterClass.Name value) {
        if (nameBuilder_ == null) {
          if (name_ != null) {
            name_ =
              playground.v1.NameOuterClass.Name.newBuilder(name_).mergeFrom(value).buildPartial();
          } else {
            name_ = value;
          }
          onChanged();
        } else {
          nameBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *name field documentation
       * </pre>
       *
       * <code>.playground.v1.Name name = 2;</code>
       */
      public Builder clearName() {
        if (nameBuilder_ == null) {
          name_ = null;
          onChanged();
        } else {
          name_ = null;
          nameBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *name field documentation
       * </pre>
       *
       * <code>.playground.v1.Name name = 2;</code>
       */
      public playground.v1.NameOuterClass.Name.Builder getNameBuilder() {
        
        onChanged();
        return getNameFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *name field documentation
       * </pre>
       *
       * <code>.playground.v1.Name name = 2;</code>
       */
      public playground.v1.NameOuterClass.NameOrBuilder getNameOrBuilder() {
        if (nameBuilder_ != null) {
          return nameBuilder_.getMessageOrBuilder();
        } else {
          return name_ == null ?
              playground.v1.NameOuterClass.Name.getDefaultInstance() : name_;
        }
      }
      /**
       * <pre>
       *name field documentation
       * </pre>
       *
       * <code>.playground.v1.Name name = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          playground.v1.NameOuterClass.Name, playground.v1.NameOuterClass.Name.Builder, playground.v1.NameOuterClass.NameOrBuilder> 
          getNameFieldBuilder() {
        if (nameBuilder_ == null) {
          nameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              playground.v1.NameOuterClass.Name, playground.v1.NameOuterClass.Name.Builder, playground.v1.NameOuterClass.NameOrBuilder>(
                  getName(),
                  getParentForChildren(),
                  isClean());
          name_ = null;
        }
        return nameBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:playground.v1.MessageSample)
    }

    // @@protoc_insertion_point(class_scope:playground.v1.MessageSample)
    private static final playground.v1.MessageSampleOuterClass.MessageSample DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new playground.v1.MessageSampleOuterClass.MessageSample();
    }

    public static playground.v1.MessageSampleOuterClass.MessageSample getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageSample>
        PARSER = new com.google.protobuf.AbstractParser<MessageSample>() {
      @java.lang.Override
      public MessageSample parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageSample(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageSample> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageSample> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public playground.v1.MessageSampleOuterClass.MessageSample getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_playground_v1_MessageSample_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_playground_v1_MessageSample_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"playground/v1/message_sample.proto\022\rpl" +
      "ayground.v1\032\030playground/v1/name.proto\"A\n" +
      "\rMessageSample\022\r\n\005topic\030\001 \001(\005\022!\n\004name\030\002 " +
      "\001(\0132\023.playground.v1.NameB\022\252\002\017org.v1.Prot" +
      "obufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          playground.v1.NameOuterClass.getDescriptor(),
        });
    internal_static_playground_v1_MessageSample_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_playground_v1_MessageSample_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_playground_v1_MessageSample_descriptor,
        new java.lang.String[] { "Topic", "Name", });
    playground.v1.NameOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
